### ISSUE TITLE
full optimization results not saved in estimation

### ISSUE THREAD

**Issue by alanlujan91** [optimagic-dev/optimagic#491]
* estimagic version used, if any: dev
* Python version, if any:
* Operating System:

### What would you like to enhance and why? Is it related to an issue/problem?

In `estimate_msm`, when the criterion function is optimized, the only results saved are the parameters

https://github.com/OpenSourceEconomics/estimagic/blob/eb8dea711cd2ec18b46d9e6735f4ce585abe0f39/src/estimagic/estimation/estimate_msm.py#L225

it might be useful to save all of `opt_res` for diagnostics about the optimization

### Describe the solution you'd like

Saving all of `opt_res` and making it an attribute of the `MomentsResult`

**Comment by janosg** [comment]
Yes, we should definitely do that!
