### ISSUE TITLE
Use fewer examples with params DataFrame in documentation

### ISSUE THREAD

**Issue by janosg** [optimagic-dev/optimagic#509]
## Situation

The documentation still contains a few examples with `params` DataFrames that might mislead users into thinking that some functionality can only be used if a `params` DataFrame is used. In particular, if they are used together with bounds or soft bounds. 

A possible incomplete list of examples is:

- `how_to_scaling.ipynb`
- `how_to_multistart.ipynb`

## Task 

- Replace DataFrame examples by simple numpy arrays
- Use `om.Bounds` to provide bounds.

**Comment by timmens** [comment]
- `how_to_scaling.md` has been tackled in #508

**Comment by janosg** [comment]
@timmens isn't the other one also done?

**Comment by timmens** [comment]
Yes, examples in how-to multistart documentation were updated in  #513
