### ISSUE TITLE
Result processing crashes if DFOLS starts from optimum

### ISSUE THREAD

**Issue by Mv77** [optimagic-dev/optimagic#538]
### Bug description

Hi! I noticed that if you start an OLS minimization problem from an initial point that is the optimum (so that no iterations happen), `minimize` crashes with (at least) DFOLS. The issue arises in the processing of results, when trying to figure out the number of iterations the problem ran for.

### To Reproduce

Here is a minimal example:

```
import optimagic as om
import numpy as np

# A simple loss
@om.mark.least_squares
def loss(x):
    return x

x0 = np.array([0.0, 0.0])
res =  om.minimize(
    fun=loss,
    params=x0,
    algorithm="nag_dfols",
    bounds=om.Bounds(np.ones_like(x0) * -1.0, np.ones_like(x0)),
)
```

### Expected behavior

Would have expected to still get a result object, even if no iterations occurred.

### Screenshots/Error messages

The error  is
```
  File "[...]\optimagic\optimizers\nag_optimizers.py", line 633, in nag_dfols_internal
    n_iterations=int(res["n_iterations"]),
                 ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

### System

 - OS: Windows
 - Version: optimagic 0.5.0, dfo-ls 1.3.0

Thanks as always!

**Comment by janosg** [comment]
Thanks a lot for the thorough bug description! I'll have a look as soon as possible!
